#!/usr/bin/env bash

# --- all vars are exported in main script line:71 --- 
# shellcheck disable=SC2154

echo -e "${RED}$(line)${EOC}"
echo -e "${RED}[1]${EOC} - ${RED}Spoof${EOC} with ${RED}random IP's${EOC}"
echo -e "$(line)"
echo -e "${RED}[2]${EOC} - ${RED}Delete${EOC} via ${RED}shred${EOC} and ${RED}disable${EOC}"
echo -e "${RED}$(line)${EOC}"
echo 
read -rp $'\033[0;91m[*]\e[0m Enter your choice > ' logs_choice

while true:
do
    case $logs_choice in
        1)
            echo 1;

        ;;
        2) echo 2;;


        0)
            sleep 1 && break && return 0;;
        *)
            echo -e "${RED}[x]${EOC} Invalid option\n"
            sleep 0.5 && logs;;
    esac;
done;