name: Simple CI that checks bash syntax

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run ShellCheck
      run: |
        shellcheck -x -s bash terminadtedshell && echo -e "\n[+] Everything is OK\n" 